version: '3.8'

services:
  apache:
    build: .
    container_name: php-apache
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - muzik_php-net
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: musik
      MYSQL_DATABASE: sitemusica
      MYSQL_USER: musik
      MYSQL_PASSWORD: musik
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - muzik_php-net

volumes:
  db_data:

networks:
  muzik_php-net:
    external: true
